### ISSUE TITLE
API URL Not Working from Server

### ISSUE THREAD

**Issue by prayasjain** [maanavshah/stock-market-india#10]
Do you know who maintains the API URLs? If I deploy on localhost, the API's are working, but if I deploy on a server, calls fail (timeout)

**Comment by maanavshah** [comment]
Hi,

Yes you are right it will only work for localhost as I haven’t deployed it. This repository is only meant for localhost development.

Thanks,
Maanav

**Comment by maanavshah** [comment]
No, this is an endpoint maintained by NSE, I am just web scrapping it for development purpose.
